language: php
dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  include:
    - php: 5.3
      dist: precise

env:
  matrix:
    - DEPENDENCIES="--dev --no-interaction --prefer-source"
    - DEPENDENCIES="--dev --no-interaction --prefer-source --prefer-lowest --prefer-stable"

before_script:
  - composer self-update
  - composer require php-coveralls/php-coveralls '~1.0'
  - composer update $DEPENDENCIES

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v -c .coveralls.yml
