language: php
sudo: false

php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
      env: dependencies=lowest
    - php: 7.1
      env: dependencies=lowest
    - php: 7.2
      env: dependencies=lowest
    - php: 7.3
      env: dependencies=lowest
    - php: 5.6
      env: dependencies=highest
    - php: 7.1
      env: dependencies=highest
    - php: 7.2
      env: dependencies=highest
    - php: 7.3
      env: dependencies=highest

before_install:
  - composer self-update

install:
  - composer require php-coveralls/php-coveralls
  - if [ -z "$dependencies" ]; then composer install --prefer-dist; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --no-interaction --prefer-dist --prefer-lowest; fi;
  - if [ "$dependencies" = "highest" ]; then composer update --no-interaction --prefer-dist; fi;

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v -c .coveralls.yml
